package word

// The word pack, baked into the binary. Curated for a family board:
// interesting but friendly, each with a plain-language definition and an
// example a kid could read at breakfast. The day's pick cycles through the
// pack in order (word.go), so adjacent days get varied parts of speech.

var pack = []entry{
	{"petrichor", "noun", "the pleasant smell of earth after rain", "The petrichor drifted in as soon as the storm passed."},
	{"wanderlust", "noun", "a strong desire to travel", "Every spring her wanderlust flared up and the maps came out."},
	{"meticulous", "adjective", "showing great attention to detail", "He was meticulous about labeling every jar in the pantry."},
	{"serendipity", "noun", "finding something good without looking for it", "Meeting their best friends at the wrong bus stop was pure serendipity."},
	{"gumption", "noun", "courage mixed with common sense and initiative", "It took gumption to raise her hand and say the plan wouldn't work."},
	{"luminous", "adjective", "giving off light; bright or glowing", "The luminous moon lit the whole backyard."},
	{"quixotic", "adjective", "idealistic in an impractical, dreamy way", "Turning the garage into a spaceship was a quixotic summer project."},
	{"mellifluous", "adjective", "sweet-sounding; pleasant to hear", "The cellist's mellifluous playing floated up the stairs."},
	{"dawdle", "verb", "to waste time; to move slower than needed", "If you dawdle over breakfast we'll miss the bus."},
	{"ephemeral", "adjective", "lasting a very short time", "The frost flowers were ephemeral, gone by mid-morning."},
	{"resilient", "adjective", "able to bounce back from hard things", "The resilient little plant grew back after the hailstorm."},
	{"whimsy", "noun", "playful, fanciful humor", "The garden gnome wearing a tiny scarf was a touch of whimsy."},
	{"cacophony", "noun", "a harsh mix of loud sounds", "A cacophony of pots and pans meant pancakes were coming."},
	{"nimble", "adjective", "quick and light in movement or thinking", "The nimble squirrel crossed the fence like a tightrope walker."},
	{"halcyon", "adjective", "calm, peaceful, and happy, often of a past time", "They told stories of halcyon summers at the lake."},
	{"tinker", "verb", "to fiddle with something to fix or improve it", "Grandpa loves to tinker with the old radio on Sundays."},
	{"vivid", "adjective", "producing strong, clear images; very bright", "She gave a vivid account of the thunderstorm."},
	{"solace", "noun", "comfort in a time of sadness", "The dog offered quiet solace after a rough day at school."},
	{"zephyr", "noun", "a soft, gentle breeze", "A zephyr moved through the curtains at dusk."},
	{"tenacity", "noun", "the quality of not giving up", "Her tenacity finally got the stuck zipper open."},
	{"amble", "verb", "to walk at a slow, relaxed pace", "We ambled home the long way, past the bakery."},
	{"kindle", "verb", "to light a fire; to stir up interest or feeling", "One library visit kindled a lifelong love of maps."},
	{"gossamer", "noun", "something extremely light and delicate", "The spiderweb hung like gossamer between the fence posts."},
	{"earnest", "adjective", "serious and sincere in intention", "He made an earnest promise to water the plants every day."},
	{"lollygag", "verb", "to spend time aimlessly; to dawdle", "No lollygagging — the tide pools close at noon."},
	{"pristine", "adjective", "perfectly clean; in original condition", "The snow was pristine until the sled run opened."},
	{"reverie", "noun", "a pleasant daydream", "The bus ride passed in a long reverie about the beach."},
	{"stalwart", "adjective", "loyal, reliable, and hardworking", "The stalwart old wagon survived another season of camping trips."},
	{"effervescent", "adjective", "bubbly; enthusiastic and lively", "Her effervescent greeting made the whole room smile."},
	{"quench", "verb", "to satisfy thirst; to put out a fire", "Nothing quenches like cold lemonade after mowing."},
	{"labyrinth", "noun", "a complicated maze of paths", "The corn maze was a proper labyrinth this year."},
	{"placid", "adjective", "calm and peaceful, with little movement", "The lake was placid at sunrise, smooth as glass."},
	{"rummage", "verb", "to search by moving things around carelessly", "She rummaged through the junk drawer for a birthday candle."},
	{"incandescent", "adjective", "glowing with heat; brilliantly bright", "The campfire embers were incandescent long after dark."},
	{"jovial", "adjective", "cheerful and friendly", "The jovial crossing guard knows every kid by name."},
	{"knack", "noun", "a natural skill for something", "He has a knack for finding four-leaf clovers."},
	{"meander", "verb", "to wander slowly along a winding course", "The creek meanders behind the school and under the bridge."},
	{"nocturnal", "adjective", "active at night", "Raccoons are nocturnal, which explains the tipped trash can."},
	{"opulent", "adjective", "rich and luxurious", "The hotel lobby was opulent, all marble and gold."},
	{"pluck", "noun", "spirited courage", "It took pluck to sing a solo at the talent show."},
	{"quibble", "verb", "to argue about small, unimportant things", "Let's not quibble over who gets the blue cup."},
	{"radiant", "adjective", "shining brightly; glowing with joy", "She was radiant when the training wheels came off."},
	{"sagacious", "adjective", "wise and good at judgment", "The sagacious librarian knew exactly which book he needed."},
	{"trove", "noun", "a store of valuable or delightful things", "The attic turned out to be a trove of old photographs."},
	{"undulate", "verb", "to move in a smooth wave-like motion", "The wheat field undulated in the wind."},
	{"verdant", "adjective", "green with growing plants", "The verdant hills of April made the drive worth it."},
	{"wistful", "adjective", "full of gentle longing", "He grew wistful looking at last summer's photos."},
	{"yonder", "adverb", "at some distance; over there", "The good blackberries grow yonder, past the old gate."},
	{"zenith", "noun", "the highest point", "The kite hung at its zenith, a speck against the blue."},
	{"alacrity", "noun", "cheerful readiness or eagerness", "She accepted the ice-cream errand with alacrity."},
	{"bumblebee", "noun", "a large, fuzzy, gentle bee", "A bumblebee worked the lavender all afternoon."},
	{"cascade", "noun", "a small waterfall; something falling in waves", "A cascade of marbles rolled out of the closet."},
	{"dapper", "adjective", "neat and stylish in appearance", "He looked dapper in his first bow tie."},
	{"eloquent", "adjective", "expressing ideas clearly and movingly", "Her eloquent toast made grandma cry, in a good way."},
	{"frolic", "verb", "to play and move about cheerfully", "The puppies frolicked in the first snow."},
	{"glimmer", "noun", "a faint or wavering light; a small sign", "There was a glimmer of hope for a snow day."},
	{"hearth", "noun", "the floor of a fireplace; the warm center of a home", "Everyone gathered at the hearth to dry their mittens."},
	{"intrepid", "adjective", "fearless and adventurous", "The intrepid toddler summited the couch again."},
	{"jubilant", "adjective", "feeling great joy, especially after a success", "The team was jubilant after the extra-inning win."},
	{"kaleidoscope", "noun", "a constantly changing pattern of shapes and colors", "Autumn turned the park into a kaleidoscope."},
	{"lark", "noun", "something done for fun or adventure", "They biked to the next town just for a lark."},
	{"mirth", "noun", "laughter and amusement", "The kitchen filled with mirth over the pancake flip gone wrong."},
	{"nifty", "adjective", "particularly clever or neat", "That's a nifty trick for peeling garlic."},
	{"oasis", "noun", "a pleasant, calm place in the middle of somewhere hectic", "The hammock is her oasis on busy weekends."},
	{"panache", "noun", "flamboyant confidence and style", "He served the grilled cheese with surprising panache."},
	{"quaint", "adjective", "attractively old-fashioned", "They stopped at a quaint diner with pie under glass domes."},
	{"rambunctious", "adjective", "uncontrollably exuberant; boisterous", "The rambunctious cousins turned the yard into a stadium."},
	{"scrumptious", "adjective", "extremely delicious", "The peach cobbler was scrumptious, especially warm."},
	{"tranquil", "adjective", "free from disturbance; calm", "The house is tranquil for about ten minutes each morning."},
	{"ubiquitous", "adjective", "seeming to be everywhere at once", "Glitter from the craft project is now ubiquitous."},
	{"vim", "noun", "energy and enthusiasm", "The coach was full of vim before Saturday's game."},
	{"waft", "verb", "to drift gently through the air", "The smell of cinnamon rolls wafted upstairs."},
	{"xylophone", "noun", "an instrument of tuned bars struck with mallets", "The xylophone solo was the recital's surprise hit."},
	{"yearn", "verb", "to long for something deeply", "By February the garden yearns for spring."},
	{"zestful", "adjective", "full of enjoyment and energy", "Her zestful retelling made the fishing trip sound epic."},
	{"brouhaha", "noun", "a noisy and overexcited fuss", "There was a brouhaha over the last slice of pizza."},
	{"copacetic", "adjective", "in excellent order; completely fine", "Homework done, lunches packed — everything's copacetic."},
	{"dulcet", "adjective", "sweet and soothing to hear", "The dulcet hum of the fan put the baby to sleep."},
	{"ebullient", "adjective", "overflowing with cheerfulness and energy", "The ebullient crowd sang along to every song."},
	{"flabbergasted", "adjective", "utterly astonished", "She was flabbergasted to win the raffle twice."},
	{"gallivant", "verb", "to roam about looking for fun", "They spent the whole holiday gallivanting around the coast."},
	{"hullabaloo", "noun", "a commotion or uproar", "The escaped hamster caused quite a hullabaloo."},
	{"idyllic", "adjective", "extremely peaceful and picturesque", "The cabin weekend was idyllic — rain on the roof and no wifi."},
	{"jamboree", "noun", "a large, lively celebration", "The block party grew into a full jamboree by evening."},
	{"kerfuffle", "noun", "a minor fuss or commotion", "There was a kerfuffle over matching socks this morning."},
	{"lackadaisical", "adjective", "without enthusiasm or effort", "The cat gave a lackadaisical swat at the toy and went back to sleep."},
	{"moxie", "noun", "determination and nerve", "It took moxie to ask the chef for her secret recipe."},
	{"nostalgia", "noun", "warm longing for the past", "The mixtape hit them both with a wave of nostalgia."},
	{"onomatopoeia", "noun", "a word that sounds like what it means", "Buzz, hiss, and clang are all onomatopoeia."},
	{"persnickety", "adjective", "fussy about small details", "He's persnickety about how the towels are folded."},
	{"quintessential", "adjective", "the most perfect example of something", "A lemonade stand is the quintessential summer project."},
	{"ruckus", "noun", "a noisy disturbance", "The blue jays raised a ruckus over the feeder."},
	{"spelunking", "noun", "exploring caves as a hobby", "The scouts went spelunking in the limestone caverns."},
	{"twilight", "noun", "the soft light just after sunset", "Fireflies come out at twilight in July."},
	{"umbrage", "noun", "offense or annoyance", "The cat took umbrage at the new kitten's confidence."},
	{"vermilion", "noun", "a brilliant red color", "The maple out front turns vermilion every October."},
	{"whirligig", "noun", "something that spins; a spinning toy", "The garden whirligig spun madly in the storm."},
	{"yesteryear", "noun", "a time in the past, remembered fondly", "The fair keeps the games of yesteryear alive."},
	{"zeal", "noun", "great energy in pursuit of something", "She attacked the leaf pile with rake-swinging zeal."},
}
