/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.ts
 * Command: astryx theme build src/theme.ts --out src/theme.css
 * Generated: 2026-07-03T05:08:05.747Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const hearthTheme: DefinedTheme;
